import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import RainbowProvider from "@/context/Provider";
import ContractProvider from "@/context/ContracProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContractProvider>
          <RainbowProvider>
            <AppProvider>{children}</AppProvider>
          </RainbowProvider>
        </ContractProvider>
      </body>
    </html>
  );
}
