import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import RainbowProvider from "@/context/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RainbowProvider>
          <AppProvider>{children}</AppProvider>
        </RainbowProvider>
      </body>
    </html>
  );
}
